const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf-8');
const start = code.indexOf('export const PADDLES: Paddle[] = [');
const end = code.indexOf('];', start) + 2;
const newPaddles = `export const PADDLES: Paddle[] = [
  {
    id: 'test-grip',
    name: 'Luzz Training Grip (Test)',
    price: 1.00,
    description: 'A cheap $1.00 item for you to test real-money checkout before buying standard paddles.',
    features: ['Real checkout test', 'Super cheap', 'Standard shipping'],
    color: 'from-gray-400 to-gray-500',
    icon: Star,
    imageUrl: '/images/luzz-covers-close.jpg',
  },
  {
    id: 'pro-cannon',
    name: 'Pro-Cannon',
    price: 159.99,
    description: 'The ultimate weapon for precision and baseline power. Features a Carbon Fiber T700 face for massive pop and spin.',
    features: ['Carbon Fiber T700 Face', 'Explosive Core', 'Pastel Edge Guard'],
    color: 'from-pink-400 to-cyan-300',
    icon: Target,
    imageUrl: '/images/pro-cannon.jpg',
  },
  {
    id: 'pro-4-tornazo',
    name: 'Pro-4 Tornazo',
    price: 149.99,
    description: 'Unleash a whirlwind of spin and control. Built with PEBAZ + CORE technology for an unbeatable soft touch.',
    features: ['PEBAZ + CORE', 'Aero-curve Shape', 'Purple Accent Guard'],
    color: 'from-purple-500 to-indigo-400',
    icon: Zap,
    imageUrl: '/images/tornazo.jpg',
  },
  {
    id: 'pro-blade-2',
    name: 'Pro-Blade 2',
    price: 169.99,
    description: 'Tournament-ready performance. Luzz UPA approved with Carbon Fiber T700 for aggressive drives and blocks.',
    features: ['Carbon Fiber T700', 'Luzz UPA Approved', 'Neon Blue Edge Guard'],
    color: 'from-blue-600 to-cyan-500',
    icon: Flame,
    imageUrl: '/images/pro-blade-2.jpg',
  },
  {
    id: 'pro-blade-2-bundle',
    name: 'Pro-Blade 2 (Bundle)',
    price: 189.99,
    description: 'The Pro-Blade 2 bundled with extra overgrips and a premium cover. Maximize your court presence.',
    features: ['Carbon Fiber T700', 'Bundle Accessories', 'Neon Blue Edge Guard'],
    color: 'from-cyan-500 to-blue-700',
    icon: Flame,
    imageUrl: '/images/pro-blade-2-action.jpg',
  },
  {
    id: 'pro-4-inferno',
    name: 'Pro-4 Inferno',
    price: 154.99,
    description: 'Turn up the heat on the court. The Pro-4 Inferno features an advanced PP-Poly core and an aggressive pink-to-blue gradient aesthetic.',
    features: ['PP-Poly Core', 'Vibrant Edge Guard', 'Aerodynamic Profile'],
    color: 'from-pink-500 to-blue-500',
    icon: Flame,
    imageUrl: '/images/pro-4-inferno.jpg',
  },
  {
    id: 'golden-dragon',
    name: 'Golden Dragon Edition',
    price: 199.99,
    description: 'A masterpiece of design and performance. The limited Golden Dragon edition commands respect with its custom illustration and raw carbon face.',
    features: ['Custom Dragon Artwork', 'Raw Carbon Face', 'Premium Leather Grip'],
    color: 'from-yellow-600 to-black',
    icon: Zap,
    imageUrl: '/images/golden-dragon-edition.jpg',
  },
  {
    id: 'obsidian-marble',
    name: 'Obsidian Marble',
    price: 179.99,
    description: 'Where luxury meets tournament-level play. Features a stunning fluid art design and an edge-to-edge textured sweet spot for maximum spin.',
    features: ['Marble Fluid Artwork', 'Textured Friction Face', 'Massive Sweet Spot'],
    color: 'from-gray-900 to-yellow-500',
    icon: Star,
    imageUrl: '/images/obsidian-marble.jpg',
  },
  {
    id: 'neon-sunset',
    name: 'Neon Sunset',
    price: 139.99,
    description: 'Stand out from the baseline. The Neon Sunset paddle captures the vibe with its striking gradient edge guard and lightweight honeycomb core.',
    features: ['Honeycomb Core', 'Lightweight Design', 'Gradient Aesthetic'],
    color: 'from-pink-500 to-purple-500',
    icon: Heart,
    imageUrl: '/images/neon-sunset.jpg',
  },
  {
    id: 'pro2-saber',
    name: 'Pro2 Saber',
    price: 159.99,
    description: 'Slice through the competition. The Pro2 Saber features sharp pink vector lines and an aerodynamic profile for lightning-fast hand speed at the kitchen.',
    features: ['Aerodynamic Design', 'Vector Line Aesthetic', 'High Deflection Face'],
    color: 'from-pink-600 to-black',
    icon: Zap,
    imageUrl: '/images/pro2-saber.jpg',
  },
  {
    id: 'luzz-sunrise',
    name: 'Luzz Sunrise',
    price: 164.99,
    description: 'Bring the dawn to the court. The Luzz Sunrise features a breathtaking painted landscape of a sunrise over the mountains, built on a responsive fiberglass face.',
    features: ['Painted Sunrise Artwork', 'Fiberglass Face', 'Comfort Grip'],
    color: 'from-orange-500 to-yellow-400',
    icon: Flame,
    imageUrl: '/images/luzz-sunrise.jpg',
  },
  {
    id: 'butterfly-dream',
    name: 'Butterfly Dream',
    price: 149.99,
    description: 'Float like a butterfly on the court. This model features a delicate pastel gradient with white butterfly motifs, offering a soft touch and exceptional control.',
    features: ['Pastel Butterfly Design', 'Soft Touch Control', 'Lightweight Build'],
    color: 'from-blue-200 to-pink-200',
    icon: Heart,
    imageUrl: '/images/butterfly-dream.jpg',
  },
  {
    id: 'kung-fu-panda',
    name: 'Dragon Warrior Edition',
    price: 219.99,
    description: 'Channel your inner Dragon Warrior. This exclusive DreamWorks Kung Fu Panda collaboration features a Carbon Fiber T700 face and custom Po artwork.',
    features: ['Carbon Fiber T700', 'Kung Fu Panda Collab', 'Exclusive White Trim'],
    color: 'from-gray-900 to-gray-700',
    icon: Flame,
    imageUrl: '/images/kung-fu-panda-collab.jpg',
  },
  {
    id: 'pickleball-net',
    name: 'Luzz Pro Tournament Net',
    price: 249.99,
    description: 'Set up court anywhere. The Luzz Pro Tournament Net is regulation size, features lockable caster wheels, and boasts a heavy-duty powder-coated steel frame.',
    features: ['Regulation Size', 'Lockable Caster Wheels', 'Powder-Coated Steel'],
    color: 'from-gray-800 to-black',
    icon: Target,
    imageUrl: '/images/pickleball-net.jpg',
  },
  {
    id: 'luzz-covers',
    name: 'Luzz Paddle Covers',
    price: 24.99,
    description: 'Protect your investment with these premium, form-fitting neoprene Luzz paddle covers. Includes a 2-pack.',
    features: ['Premium Neoprene', 'Zipper Closure', 'Fits All Luzz Paddles'],
    color: 'from-gray-800 to-gray-600',
    icon: Star,
    imageUrl: '/images/luzz-covers.jpg',
  }
];`;
code = code.substring(0, start) + newPaddles + code.substring(end);
fs.writeFileSync('src/App.tsx', code);
